// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBuPQYqN3xdYC6ifU7XoV_b9RFp55uRpU',
    appId: '1:896280454677:web:fb64ce7047b25892afd01c',
    messagingSenderId: '896280454677',
    projectId: 'calendar-app-4626d',
    authDomain: 'calendar-app-4626d.firebaseapp.com',
    storageBucket: 'calendar-app-4626d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTj74UCV6sXMmMESipW_uzS2dsGDvGwTA',
    appId: '1:896280454677:android:6264051bc836b7b2afd01c',
    messagingSenderId: '896280454677',
    projectId: 'calendar-app-4626d',
    storageBucket: 'calendar-app-4626d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnG_DOWBAn-9MHlsV6NypA7WGTYB_hrIY',
    appId: '1:896280454677:ios:501177a645339713afd01c',
    messagingSenderId: '896280454677',
    projectId: 'calendar-app-4626d',
    storageBucket: 'calendar-app-4626d.firebasestorage.app',
    iosBundleId: 'com.example.calenderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnG_DOWBAn-9MHlsV6NypA7WGTYB_hrIY',
    appId: '1:896280454677:ios:501177a645339713afd01c',
    messagingSenderId: '896280454677',
    projectId: 'calendar-app-4626d',
    storageBucket: 'calendar-app-4626d.firebasestorage.app',
    iosBundleId: 'com.example.calenderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBuPQYqN3xdYC6ifU7XoV_b9RFp55uRpU',
    appId: '1:896280454677:web:49908abf739c5017afd01c',
    messagingSenderId: '896280454677',
    projectId: 'calendar-app-4626d',
    authDomain: 'calendar-app-4626d.firebaseapp.com',
    storageBucket: 'calendar-app-4626d.firebasestorage.app',
  );
}
